# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 16:44
from __future__ import unicode_literals

from django.db import migrations
import oxdjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160219_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='alternativeNames',
            field=oxdjango.fields.TupleField(default=()),
        ),
    ]
