# Generated by Django 4.2.3 on 2023-07-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='text',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='text',
            name='status',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='text',
            name='type',
            field=models.CharField(default='html', max_length=255),
        ),
    ]
