# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('target', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IDAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(max_length=255, unique=True)),
                ('new', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LayerAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(max_length=255, unique=True)),
                ('new', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(max_length=255, unique=True)),
                ('new', models.CharField(max_length=255)),
            ],
        ),
    ]
