# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-19 17:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

def remove_posterframes(apps, schema_editor):
    Collection = apps.get_model("documentcollection", "Collection")
    for c in Collection.objects.exclude(poster_frames=None):
        c.poster_frames = []
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('documentcollection', '0003_jsonfield'),
    ]

    operations = [
        migrations.RunPython(remove_posterframes),
    ]
