# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imdbId',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
