# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ox.django.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0002_annotation_clip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('defined', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=1024)),
                ('alternativeNames', ox.django.fields.TupleField(default=[])),
                ('name_sort', models.CharField(db_index=True, max_length=200)),
                ('name_find', models.TextField(default=b'', editable=False)),
                ('geoname', models.CharField(max_length=1024, null=True)),
                ('geoname_sort', models.CharField(db_index=True, max_length=1024, null=True)),
                ('countryCode', models.CharField(db_index=True, default=b'', max_length=16)),
                ('wikipediaId', models.CharField(blank=True, max_length=1000)),
                ('type', models.CharField(db_index=True, default=b'', max_length=1000)),
                ('south', models.FloatField(db_index=True, default=None, null=True)),
                ('west', models.FloatField(db_index=True, default=None, null=True)),
                ('north', models.FloatField(db_index=True, default=None, null=True)),
                ('east', models.FloatField(db_index=True, default=None, null=True)),
                ('lat', models.FloatField(db_index=True, default=None, null=True)),
                ('lng', models.FloatField(db_index=True, default=None, null=True)),
                ('area', models.FloatField(db_index=True, default=None, null=True)),
                ('matches', models.IntegerField(db_index=True, default=0)),
                ('annotations', models.ManyToManyField(blank=True, related_name='places', to='annotation.Annotation')),
                ('items', models.ManyToManyField(blank=True, related_name='places', to='item.Item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_sort',),
            },
        ),
    ]
