# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 16:44
from __future__ import unicode_literals

from django.db import migrations
import oxdjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='alternativeNames',
            field=oxdjango.fields.TupleField(default=()),
        ),
    ]
