# Generated by Django 4.2.3 on 2023-07-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20160304_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='countryCode',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_find',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=1000),
        ),
    ]
