# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

import clip.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('aspect_ratio', models.FloatField(default=0)),
                ('user', models.IntegerField(db_index=True, null=True)),
                ('start', models.FloatField(db_index=True, default=-1)),
                ('end', models.FloatField(default=-1)),
                ('duration', models.FloatField(db_index=True, default=0)),
                ('hue', models.FloatField(db_index=True, default=0)),
                ('saturation', models.FloatField(db_index=True, default=0)),
                ('lightness', models.FloatField(db_index=True, default=0)),
                ('volume', models.FloatField(db_index=True, default=0, null=True)),
                ('sortvalue', models.CharField(db_index=True, max_length=1000, null=True)),
                ('findvalue', models.TextField(db_index=True, null=True)),
                ('places', models.BooleanField(db_index=True, default=False)),
                ('events', models.BooleanField(db_index=True, default=False)),
                ('keywords', models.BooleanField(db_index=True, default=False)),
                ('descriptions', models.BooleanField(db_index=True, default=False)),
                ('transcripts', models.BooleanField(db_index=True, default=False)),
            ],
            bases=(clip.models.MetaClip, models.Model),
        ),
        migrations.CreateModel(
            name='Random',
            fields=[
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clip.Clip')),
                ('random', models.BigIntegerField(db_index=True, null=True)),
            ],
        ),
    ]
