# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clip', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='item.Item'),
        ),
        migrations.AddField(
            model_name='clip',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_clips', to='item.ItemSort'),
        ),
        migrations.AlterUniqueTogether(
            name='clip',
            unique_together=set([('item', 'start', 'end')]),
        ),
    ]
