# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0002_auto_20160219_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipRandom',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clip.Clip')),
            ],
        ),
        migrations.RemoveField(
            model_name='random',
            name='clip',
        ),
        migrations.DeleteModel(
            name='Random',
        ),
    ]
