# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lang', models.CharField(max_length=8, verbose_name='language')),
                ('key', models.CharField(max_length=4096, verbose_name='key')),
                ('value', models.CharField(blank=True, default=None, max_length=4096, null=True, verbose_name='translation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([('key', 'lang')]),
        ),
    ]
