# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='type',
            field=models.IntegerField(default=0, verbose_name='type'),
        ),
    ]
