# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:08
from __future__ import unicode_literals

from django.db import migrations
import oxdjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('entity', '0002_auto_20160304_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentproperties',
            name='data',
            field=oxdjango.fields.DictField(default={}),
        ),
    ]
