# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_documentproperties_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproperties',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentproperties', to='document.Document'),
        ),
    ]
