# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=1)),
                ('pages', models.IntegerField(default=-1)),
                ('width', models.IntegerField(default=-1)),
                ('height', models.IntegerField(default=-1)),
                ('description', models.TextField(default=b'')),
                ('oshash', models.CharField(max_length=16, null=True, unique=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=document.models.get_path)),
                ('uploading', models.BooleanField(default=False)),
                ('name_sort', models.CharField(max_length=255, null=True)),
                ('description_sort', models.CharField(max_length=512, null=True)),
                ('dimensions_sort', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default=b'')),
                ('index', models.IntegerField(default=0)),
                ('description_sort', models.CharField(max_length=512, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='document.Document')),
            ],
        ),
    ]
