# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import oxdjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20160219_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='data',
            field=oxdjango.fields.DictField(default={}),
        ),
        migrations.AddField(
            model_name='document',
            name='rightslevel',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
