# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20161008_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('value', models.TextField(blank=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sort', serialize=False, to='document.Document')),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=1000, null=True)),
                ('id', models.CharField(db_index=True, max_length=1000, null=True)),
                ('extension', models.CharField(db_index=True, max_length=1000, null=True)),
                ('dimensions', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('size', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(db_index=True, max_length=1000, null=True)),
                ('matches', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('user', models.CharField(db_index=True, max_length=1000, null=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accessed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timesaccessed', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('rightslevel', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='find',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find', to='document.Document'),
        ),
        migrations.AlterUniqueTogether(
            name='find',
            unique_together=set([('document', 'key')]),
        ),
    ]
