# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20160219_1537'),
        ('document', '0009_add_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='annotations',
            field=models.ManyToManyField(related_name='documents', to='annotation.Annotation'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_documents',
            field=models.ManyToManyField(related_name='linking_documents', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ratio',
            field=models.FloatField(default=-1),
        ),
    ]
