# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(max_length=128, unique=True)),
                ('start', models.FloatField(db_index=True, default=-1)),
                ('end', models.FloatField(db_index=True, default=-1)),
                ('layer', models.CharField(db_index=True, max_length=255)),
                ('value', models.TextField()),
                ('findvalue', models.TextField(null=True)),
                ('sortvalue', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
