# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('sorttitle', models.CharField(max_length=1000)),
                ('sortsorttitle', models.CharField(max_length=1000)),
                ('edited', models.BooleanField(default=False)),
                ('imdbId', models.CharField(blank=True, max_length=7)),
            ],
        ),
    ]
