# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edit', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editclip', to='item.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('user', 'edit', 'section')]),
        ),
        migrations.AlterUniqueTogether(
            name='edit',
            unique_together=set([('user', 'name')]),
        ),
    ]
