# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-15 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import oxdjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_auto_20160219_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='volume',
            new_name='sortvolume',
        ),
        migrations.AddField(
            model_name='clip',
            name='volume',
            field=models.FloatField(default=1),
        ),
    ]
