# Generated by Django 4.2.3 on 2023-07-27 21:28

import django.core.serializers.json
from django.db import migrations, models
import edit.models
import oxdjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0005_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='poster_frames',
            field=oxdjango.fields.JSONField(default=list, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='edit',
            name='query',
            field=oxdjango.fields.JSONField(default=edit.models.default_query, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
