# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import oxdjango.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('index', models.IntegerField(default=0)),
                ('data', oxdjango.fields.DictField(default={}, editable=False)),
            ],
        ),
    ]
