# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(0, b'shape'), (1, b'color')], default=0)),
                ('hash', models.BigIntegerField(db_index=True, default=-9223372036854775808)),
                ('start', models.FloatField(default=-1)),
                ('end', models.FloatField(default=-1)),
                ('duration', models.FloatField(default=0)),
                ('sort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='item.ItemSort')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set([('sort', 'start', 'end', 'mode')]),
        ),
    ]
