# Generated by Django 4.2.3 on 2023-07-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='mode',
            field=models.IntegerField(choices=[(0, 'shape'), (1, 'color')], default=0),
        ),
    ]
