# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='item.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together=set([('file', 'resolution', 'format')]),
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set([('path', 'volume')]),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together=set([('file', 'position')]),
        ),
    ]
