# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 17:26
from __future__ import unicode_literals

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20160219_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='atime',
            field=models.BigIntegerField(default=archive.models.inttime, editable=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='ctime',
            field=models.BigIntegerField(default=archive.models.inttime, editable=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='mtime',
            field=models.BigIntegerField(default=archive.models.inttime, editable=False),
        ),
    ]
