# Generated by Django 4.2.3 on 2023-08-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_alter_file_extension_alter_file_id_alter_file_info_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['file', 'source', 'available'], name='archive_str_file_id_69a542_idx'),
        ),
    ]
