# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oxdjango.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('firstseen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lastseen', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('username', models.CharField(db_index=True, max_length=255, null=True)),
                ('level', models.IntegerField(db_index=True, default=0)),
                ('timesseen', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('useragent', models.CharField(max_length=4096, null=True)),
                ('windowsize', models.CharField(max_length=255, null=True)),
                ('screensize', models.CharField(max_length=255, null=True)),
                ('info', oxdjango.fields.DictField(default={})),
                ('location', models.CharField(max_length=255, null=True)),
                ('location_sort', models.CharField(max_length=255, null=True)),
                ('system', models.CharField(max_length=255, null=True)),
                ('browser', models.CharField(max_length=255, null=True)),
                ('numberoflists', models.IntegerField(default=0, null=True)),
                ('groupssort', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('files_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('newsletter', models.BooleanField(default=True)),
                ('ui', oxdjango.fields.DictField(default={})),
                ('preferences', oxdjango.fields.DictField(default={})),
                ('notes', models.TextField(default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
