# Generated by Django 3.0.10 on 2023-07-10 08:52

import django.core.serializers.json
from django.db import migrations, models
import oxdjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_json_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='torrent',
        ),
    ]
